"""GetDP problem-file templates (2D planar magnetostatics, vector potential).

Rendered with :class:`string.Template` (``$var`` substitution) because GetDP
syntax is full of braces. Regions are wired to the mesh by PHYSICAL TAG from
:class:`~axfluxmdo.solvers.gmsh_export.Linear2DLayout` — unambiguous and
independent of name embedding in the .msh.

Physics consistency: the magnet source term ``[-nu[] * br[], {d a}]`` together
with ``nu = 1/(mu0*mu_r)`` realizes the recoil line ``b = mu0*mu_r*h + Br`` —
exactly the constitutive model behind
:func:`axfluxmdo.materials.magnetic.airgap_flux_density`. Slotless residuals
therefore isolate geometric effects (inter-magnet fringing, finite iron
permeability), not material modeling differences.
"""

from __future__ import annotations

from string import Template

from axfluxmdo.geometry.axial_flux import AxialFluxMotor
from axfluxmdo.solvers.gmsh_export import Linear2DLayout

_OPEN_CIRCUIT_TEMPLATE = Template(
    """// Auto-generated by axfluxmdo: 2D planar magnetostatics, open circuit.
// Unrolled axial-flux cross-section at the mean radius; one pole pair, periodic.

Group {
  ROTOR_IRON  = Region[$rotor_iron];
  STATOR_IRON = Region[$stator_iron];
  MAGNET_N    = Region[$magnet_n];
  MAGNET_S    = Region[$magnet_s];
  AIRGAP      = Region[$airgap];
  AIR         = Region[$air];
$winding_region
  PERIODIC_LEFT  = Region[$periodic_left];
  PERIODIC_RIGHT = Region[$periodic_right];
  OUTER          = Region[$outer];

  Magnets = Region[{MAGNET_N, MAGNET_S}];
  Iron    = Region[{ROTOR_IRON, STATOR_IRON}];
  NonMag  = Region[{AIRGAP, AIR$winding_in_nonmag}];
  Domain  = Region[{Iron, Magnets, NonMag}];
}

Function {
  mu0 = 4.e-7 * Pi;
  nu[NonMag]  = 1. / mu0;
  nu[Iron]    = 1. / ($mu_r_steel * mu0);   // linear steel (Phase 4)
  nu[Magnets] = 1. / ($mu_r_magnet * mu0);
  br[MAGNET_N] = Vector[0.,  $br_t, 0.];    // axial magnetization in the unrolled frame
  br[MAGNET_S] = Vector[0., -$br_t, 0.];
}

Constraint {
  // Dirichlet listed first so it wins the shared corner nodes over the Link.
  { Name a_dirichlet; Case { { Region OUTER; Value 0.; } } }
  { Name a_periodic; Case {
      { Region PERIODIC_RIGHT; Type Link; RegionRef PERIODIC_LEFT;
        Coefficient 1.; Function Vector[X[] - $x_span, Y[], Z[]]; } } }
}

FunctionSpace {
  { Name Hcurl_a_2D; Type Form1P;
    BasisFunction {
      { Name se; NameOfCoef ae; Function BF_PerpendicularEdge;
        Support Domain; Entity NodesOf[All]; } }
    Constraint {
      { NameOfCoef ae; EntityType NodesOf; NameOfConstraint a_dirichlet; }
      { NameOfCoef ae; EntityType NodesOf; NameOfConstraint a_periodic; } } }
}

Jacobian { { Name JVol; Case { { Region All; Jacobian Vol; } } } }

Integration {
  { Name I1; Case { { Type Gauss; Case {
      { GeoElement Triangle;   NumberOfPoints 4; }
      { GeoElement Quadrangle; NumberOfPoints 4; } } } } }
}

Formulation {
  { Name MagSta_a_2D; Type FemEquation;
    Quantity { { Name a; Type Local; NameOfSpace Hcurl_a_2D; } }
    Equation {
      Galerkin { [ nu[] * Dof{d a}, {d a} ]; In Domain;  Jacobian JVol; Integration I1; }
      Galerkin { [ -nu[] * br[],    {d a} ]; In Magnets; Jacobian JVol; Integration I1; }
    } }
}

Resolution {
  { Name Magnetostatics2D;
    System { { Name S; NameOfFormulation MagSta_a_2D; } }
    Operation { Generate[S]; Solve[S]; SaveSolution[S]; } }
}

PostProcessing {
  { Name MagSta_post; NameOfFormulation MagSta_a_2D;
    Quantity {
      { Name b;  Value { Local { [ {d a} ];        In Domain; Jacobian JVol; } } }
      { Name az; Value { Local { [ CompZ[{a}] ];   In Domain; Jacobian JVol; } } } } }
}

PostOperation {
  { Name gap_field; NameOfPostProcessing MagSta_post;
    Operation {
      Print[ b, OnLine { {0., $y_mid, 0.} {$x_span, $y_mid, 0.} } { $n_samples },
             Format Table, File "$table_filename" ];
    } }
}
"""
)


def render_open_circuit_pro(
    motor: AxialFluxMotor,
    layout: Linear2DLayout,
    *,
    magnet_temp_c: float,
    n_samples: int = 720,
    table_filename: str = "gap_field.dat",
) -> str:
    """Render the open-circuit magnetostatics .pro file for a built 2D layout."""
    tags = layout.group_tags
    winding_region = ""
    winding_in_nonmag = ""
    if "WINDING" in tags:
        winding_region = f"  WINDING     = Region[{tags['WINDING']}];"
        winding_in_nonmag = ", WINDING"
    return _OPEN_CIRCUIT_TEMPLATE.substitute(
        rotor_iron=tags["ROTOR_IRON"],
        stator_iron=tags["STATOR_IRON"],
        magnet_n=tags["MAGNET_N"],
        magnet_s=tags["MAGNET_S"],
        airgap=tags["AIRGAP"],
        air=tags["AIR"],
        winding_region=winding_region,
        winding_in_nonmag=winding_in_nonmag,
        periodic_left=tags["PERIODIC_LEFT"],
        periodic_right=tags["PERIODIC_RIGHT"],
        outer=tags["OUTER"],
        mu_r_steel=repr(motor.steel.mu_r),
        mu_r_magnet=repr(motor.magnet.mu_r),
        br_t=repr(motor.magnet.remanence_at(magnet_temp_c)),
        x_span=repr(layout.x_span_m),
        y_mid=repr(layout.gap_midline_y_m),
        n_samples=n_samples,
        table_filename=table_filename,
    )
